### ISSUE TITLE
HfLA: Tables Meeting Agenda and Notes

### ISSUE THREAD

**Issue by hang-justin** [hackforla/tables#41]
### Overview
This issue tracks the agenda and notes for the Development/PM meeting

### Action Items
- [ ] Add the Date of the next meeting below
- [ ] Link the Agenda/Notes from meeting
#### Template
```
## [DATE IN YYYY-MM-DD FORMAT] Meeting Agenda

### Attendees
- 

### Prework to prep for meeting
- [ ] Review the [QA](https://github.com/hackforla/website/projects/7#column-15490305)
- [ ] Prework issues: Add notes to this meeting agenda as a discussion or FYI item (if no action needs to be taken).
- [ ] Can we improve the prework template based on something we see as a pattern?  

### FYIs (nothing needs to be done, just keeping each other informed)

### Recurring items: 
 - [ ] review any issues that are in the new issue approval column for 
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/tables/issues/assigned/ExperimentsInHonesty)
       - [ ] [Justin](https://github.com/hackforla/tables/issues/assigned/hang-justin)

### New Items 
add issue numbers to be discussed and any notes that will be helpful
1. [INITIALS] - Issue


### Notes from meeting
- Notetaker: @(person)
- 

### Tasks
- [ ] 

### Items for next week's agenda
- [ ] 
```

Prior and upcoming meetings

**Comment by hang-justin** [comment]
## 2023-05-12 Meeting Agenda

PLACEHOLDER - Will Add Notes

**Comment by hang-justin** [comment]
## 2023-05-19 Meeting Agenda

### Attendees
- Bonnie Wolfe
- Justin Hang

### Prework to prep for meeting
- [ ] Review the [QA](https://github.com/hackforla/website/projects/7#column-15490305)
- [ ] Prework issues: Add notes to this meeting agenda as a discussion or FYI item (if no action needs to be taken).
- [ ] Can we improve the prework template based on something we see as a pattern?  

### FYIs (nothing needs to be done, just keeping each other informed)

### Recurring items: 
 - [ ] review any issues that are in the new issue approval column for 
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/tables/issues/assigned/ExperimentsInHonesty)
       - [ ] [Justin](https://github.com/hackforla/tables/issues/assigned/hang-justin)

### New Items 
add issue numbers to be discussed and any notes that will be helpful
1. [INITIALS] - Issue


### Notes from meeting
- 

### Tasks
- [ ] 

### Items for next week's agenda
- [ ]

**Comment by hang-justin** [comment]
## 2023-05-26 Meeting Agenda

### Attendees
- Aishwarya Harikumar
- Harrison Katz
- Bonnie Wolfe
- Justin Hang

### Prework to prep for meeting
- [ ] Review the [QA](https://github.com/hackforla/website/projects/7#column-15490305)
- [ ] Prework issues: Add notes to this meeting agenda as a discussion or FYI item (if no action needs to be taken).
- [ ] Can we improve the prework template based on something we see as a pattern?  

### FYIs (nothing needs to be done, just keeping each other informed)

### Recurring items: 
 - [ ] review any issues that are in the new issue approval column for 
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/tables/issues/assigned/ExperimentsInHonesty)
       - [ ] [Justin](https://github.com/hackforla/tables/issues/assigned/hang-justin)

### New Items 
add issue numbers to be discussed and any notes that will be helpful

1. JH: Review calendar invite automation
2. JH: Review weekly website meeting form


### Notes from meeting
- Notetaker: @hang-justin 

### Tasks
- [ ] JH: Make the new tables globally available
- [ ] JH: Set editor permissions for proper users (Justin and Harrison)
- [ ] HK: Update dev environment to reflect prod

### Items for next week's agenda
- [ ]

**Comment by hang-justin** [comment]
Close. Duplicate issue of #21
