### ISSUE TITLE
Test implementation with less recurring dates

### ISSUE THREAD

**Issue by hkatzdev** [hackforla/tables#45]
### Dependency
- Wait to see if the Zoom api to add people to a meeting registration works more reliably than adding to calendar invites.

### Overview
Test if less recurring dates will prevent the calendar from timing out.

### Action Items
- [ ] Make reoccurring events with lengths of 3, 6, 9 and 12 months.
- [ ] Add 200 users to said events.
- [ ] Attempt to use the Google API and see if it times out.

**Comment by ExperimentsInHonesty** [comment]
We no longer need to do this, because we are using the zoom api to add everyone to zoom registration.
