### ISSUE TITLE
Tables: Onboard / Offboard Team member

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tables#56]
### Dependency
- [ ] Until we have a Team member to onboard or offboard

### Overview
We need to have a checklist of items to do when a team meber onboard and offboards so that the process can be consistent and fast.

#### Details
- If you are looking for the onboarding/offboarding issue for PMs https://github.com/hackforla/tables/issues/31

### Date Updated
(insert date you created this issue and keep updating the date each time the org template change are integrated)

### Action Items
- [ ] Check to see if the org template for this process has new steps in it, and if it does, update this  issue and its template with content and add the last date you updated the template below
- [ ] Copy template to comment below
- [ ] Add name of person
- [ ] Check off as done

```
#### Onboard
- [ ] Slack channel membership
  - [ ] tables
- [ ] Add to Google calendar invites
   - [ ] Wednesday - team meeting
- [ ] Add to team page on repo
- [ ] Google Drive
   - [ ] Add to drive as Contributor
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
- [ ] GitHub
     - [ ] Add to team write team
     - [ ] Add to read vault
     - [ ] Assign them to the issue #21 and add them to role call and accountability check
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] tables
       - [ ] Tables - Zoom@
- [ ] Add to email address(s) forwarding if they need it
   - [ ] tables@hackforla.org 
- [ ] Train how to 
   - [ ] login to team account
   - [ ] setup chrome shortcut for adding to desktop
   - [ ] vault and accounts
- [ ] Tables
   - [ ] Share Volunteer Table to email as an Editor
```
```
#### Offboard
- [ ] Remove from Google calendar invite
   - [ ] Wednesday - team meeting
- [ ] WIKI
   - [ ] regenerate team page to update the member from current to former
- [ ] 1password setup
    - [ ] remove from team vaults
       - [ ] tables
       - [ ] Tables - Zoom@
- [ ] Google Drive
   - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] read team - if they are a maintainer, change to member.
     - [ ] write team, remove
     - [ ] remove them from issue #21 and remove them from role call and accountability check
     - [ ] Review all issues the person you are offboarding might be assigned to, by using the Assignee filter on the [issue tab](https://github.com/hackforla/tables/issues)
- [ ] Figma
  - [ ] remove from team
- [ ] Help them delete the desktop shortcut to email address if they made one.
- [ ] Remove from email address(s) forwarding
   - [ ] tables@hackforla.org (if they are on it)
```

### Resources/Instructions
- [1password.com](https://1password.com/)
- [Tables Google Drive Link](https://drive.google.com/drive/folders/0AO5HWG9daZAtUk9PVA)
- [Tables Team Roster](https://docs.google.com/spreadsheets/d/13LKG5lGXpCD8CvtD9zAvj70pxKjJxAJ2vwltedibzDk/edit?usp=share_link)
- Check public at [people page](https://github.com/orgs/hackforla/people)
- [Table GitHub Teams](https://github.com/orgs/hackforla/teams/tables)
   - [base (read)](https://github.com/orgs/hackforla/teams/tables/members?add=true)
   - [write](https://github.com/orgs/hackforla/teams/tables-write/members?add=true)
   - [admin](https://github.com/orgs/hackforla/teams/tables-admin/members?add=true)
   - [other]
- WIKI team page: https://github.com/hackforla/tables/blob/main/dev-docs/team.md
- [Volunteer Table](https://tables.area120.google.com/u/0/workspace/bHKoRlcCZyubeRsnie2OgH/table/a8Fi8xyvbbq0gWnJv5p_tB)
- [Tables Figma](https://www.figma.com/files/team/1307118904876786325/tables-project's-team?fuid=775836858007206739)
- Shortcut for adding a profile to the desktop:  chrome://settings/manageProfile
- Tutorials
  - [Forward emails to team members](https://github.com/hackforla/product-management/wiki/Forward-emails-to-team-members)
---
[org template](https://raw.githubusercontent.com/hackforla/.github/main/.github/ISSUE_TEMPLATE/onboard---offboard--product.md) updated 2022-02-23
[Changelog](https://github.com/hackforla/product-management/wiki/Onboard-Offboard-Changelog)

**Comment by aishwaryaharikumar** [comment]
#### Offboard - 20233-09-01 Justin Hang
- [x] Remove from Google calendar invite
   - [x] Friday - team meeting
- [ ] WIKI - we don't have it as it is a private repo
  - [ ] move to new place on team page (we don't have a github wiki, because this repo is private)
- [x] 1password setup
    - [x] remove from team vaults
       - [x] tables
       - [x] Zoom vault
- [x] Google Drive
   - [x] demote to viewer
- [x] Roster
  - [x] mark as inactive
- [x] GitHub
     - [x] read team - if they are a maintainer, change to member.
     - [x] write team, remove
- [ ] Figma - we don't have one yet
  - [ ] remove from team
- [ ] Help them delete the desktop shortcut to email address if they made one.
- [ ] Remove from email address(s)
   - [x] tables@hackforla.org (if they are on it)
- [ ] Remove from Social Media Accounts with role assignment (currently not using)
   - [ ] Facebook

**Comment by aishwaryaharikumar** [comment]
#### Offboard -2023-09-20 Sharon Inu
- [ ] Remove from Google calendar invite
   - [ ] Friday - team meeting
- [ ] WIKI
  - [ ] move to new place on team page (we don't have a github wiki, because this repo is private)
- [ ] 1password setup
    - [ ] remove from team vaults
       - [ ] tables
       - [ ] Zoom vault
- [ ] Google Drive
   - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] read team - if they are a maintainer, change to member.
     - [ ] write team, remove
- [ ] Figma  - there isn't one yet
  - [ ] remove from team
- [ ] Help them delete the desktop shortcut to email address if they made one.
- [ ] Remove from email address(s) forwarding
   - [ ] tables@hackforla.org (if they are on it)
- [ ] Remove from Social Media Accounts with role assignment (currently not using)
   - [ ] Facebook

**Comment by jetchen08** [comment]
Need to do a one-time cleanup of all people who used to be on the project and offboard them.

**Comment by ExperimentsInHonesty** [comment]
#### Offboard 2024-03-28
- Jenny Chu
- Michelle Lam
- Grace Fredrick
- Aishwarya Harikumar
- Justin Hang
- Sharon Lnu
- Kenny Tram
- Toe Arkar
- Tyler Kontra
- [x] Remove from Google calendar invite
   - [x] Wednesday - team meeting
- [x] WIKI
  - [x] move to new place on team page (we don't have a github wiki, because this repo is private)
- [x] 1password setup
    - [x] remove from team vaults
       - [x] tables
       - [x] Tables - Zoom@
- [x] Google Drive
   - [x] remove
- [x] Roster
  - [x] mark as inactive
- [x] GitHub
     - [x] read team - if they are a maintainer, change to member.
     - [x] write team, remove
     - [x] remove them from issue #21 and remove them from role call and accountability check
     - [x] Review all issues the person you are offboarding might be assigned to, by using the Assignee filter on the [issue tab](https://github.com/hackforla/tables/issues)
- [x] Figma (we don't have figma yet)
  - [ ] remove from team 
- [x] Help them delete the desktop shortcut to email address, if they made one.
- [x] Remove from email address(s) forwarding
   - [x] tables@hackforla.org (if they are on it)

**Comment by lilykat7** [comment]
We need to offboard the following people:
- @wesley115

**Comment by lilykat7** [comment]
#### Onboard Kenalpha Kipyegon 2024-05-08
- [x] Slack channel membership
  - [x] tables
- [x] Add to Google calendar invites
   - [x] Wednesday - team meeting
- [x] Add to team page on repo
- [x] Google Drive
   - [x] Add to drive as Contributor
- [x] Roster
  - [x] Send link
  - [x] Team member adds themselves
  - [x] Check for Public and note in roster
- [x] GitHub
     - [x] Add to team write team
     - [x] Add to read vault
     - [x] Assign them to the issue #21 and add them to role call and accountability check
- [x] Figma
  - [x] invite
  - [x] acceptance
- [x] 1password 
     - [x] invitation
     - [x] acceptance
     - [x] add to vaults
       - [x] tables
       - [x] Tables - Zoom@
- [x] Add to email address(s) forwarding if they need it
   - [x] tables@hackforla.org 
- [ ] Train how to 
   - [x] login to team account
   - [ ] setup chrome shortcut for adding to desktop
   - [x] vault and accounts
- [x] Tables
   - [x] Share Volunteer Table to email as an Editor

**Comment by lilykat7** [comment]
#### Offboard Kenalpha Kipyegon 2024-05-30
- [x] Remove from Google calendar invite
   - [x] Wednesday - team meeting
- [x] WIKI
   - [x] regenerate team page to update the member from current to former
- [ ] 1password setup
    - [ ] remove from team vaults
       - [ ] tables
       - [ ] Tables - Zoom@
- [x] Google Drive
   - [x] demote to viewer
- [x] Roster
  - [x] mark as inactive
- [x] GitHub
     - [x] read team - if they are a maintainer, change to member.
     - [x] write team, remove
     - [x] remove them from issue #21 and remove them from role call and accountability check
     - [x] Review all issues the person you are offboarding might be assigned to, by using the Assignee filter on the [issue tab](https://github.com/hackforla/tables/issues)
- [ ] Figma
  - [ ] remove from team
- [ ] Help them delete the desktop shortcut to email address if they made one.
- [ ] Remove from email address(s) forwarding
   - [ ] tables@hackforla.org (if they are on it)

**Comment by lilykat7** [comment]
#### Onboard Tyler Lippert 2024-05-23
- [x] Slack channel membership
  - [x] tables
- [x] Add to Google calendar invites
   - [x] Wednesday - team meeting
- [x] Add to team page on repo
- [x] Google Drive
   - [x] Add to drive as Contributor
- [x] Roster
  - [x] Send link
  - [x] Team member adds themselves
  - [x] Check for Public and note in roster
- [x] GitHub
     - [x] Add to team write team
     - [x] Add to read vault
     - [x] Assign them to the issue #21 and add them to role call and accountability check
- [ ] Figma
  - [x] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] tables
       - [ ] Tables - Zoom@
- [ ] Add to email address(s) forwarding if they need it
   - [ ] tables@hackforla.org 
- [ ] Train how to 
   - [ ] login to team account
   - [ ] setup chrome shortcut for adding to desktop
   - [ ] vault and accounts
- [ ] Tables
   - [ ] Share Volunteer Table to email as an Editor

**Comment by ExperimentsInHonesty** [comment]
#### Onboard 2025-09-24 Mirgas
- [x] Slack channel membership
  - [x] tables
- [x] Add to Google calendar invites
   - [x] Wednesday - team meeting
- [ ] Add to team page on repo
- [x] Google Drive
   - [x] Add to drive as Contributor
- [x] Roster
  - [x] Send link
  - [x] Team member adds themselves
  - [x] Check for Public and note in roster
- [ ] GitHub
     - [x] Add to team write team
     - [x] Add to read vault
     - [x] Assign them to the issue #21 and add them to role call and accountability check
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [x] 1password 
     - [x] invitation
     - [x] acceptance
     - [ ] add to vaults
       - [ ] tables
       - [ ] Tables - Zoom@
- [ ] Add to email address(s) forwarding if they need it
   - [ ] tables@hackforla.org 
- [ ] Train how to 
   - [ ] login to team account
   - [ ] setup chrome shortcut for adding to desktop
   - [ ] vault and accounts
- [ ] Tables
   - [ ] Share Volunteer Table to email as an Editor
