### ISSUE TITLE
Tables: PM Agenda

### ISSUE THREAD

**Issue by jetchen08** [hackforla/tables#60]
### Overview
This issue tracks the agenda for our weekly meetings

#### Issue Template
```
## [Date ]  Meeting Agenda

### Prework to prep for meeting
- [ ] #30

### Recurring items:
 - [ ] review any issues in [Q&A column](https://github.com/hackforla/tables/projects/1#column-15912779)
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/tables/projects/1#column-15912776)
 - [ ] Review issue for any new questions https://github.com/hackforla/tables/issues/54
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Lily Ng](https://github.com/hackforla/tables/issues/assigned/lilykat7)
       - [ ] [Bonnie](https://github.com/hackforla/tables/issues/assigned/ExperimentsInHonesty)
       - [ ] [Jessica C.](https://github.com/hackforla/tables/issues/assigned/jetchen08)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting
#### Recording
 - [ ] was there a recording made
 - [ ] did it get uploaded to the [folder](https://drive.google.com/drive/u/0/folders/1JkyEid3JMyXyXeQg7cn9m6nACv6CKP8F)

### Task Items
```

### Links to other agenda issues for your team 
(so that you can easily post on their agendas items that come up at yours)

### Past and Future meetings

**Comment by jetchen08** [comment]
## 2023-11-09  Meeting Agenda

### Prework to prep for meeting
- [ ] #30

### Recurring items:
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/tables/projects/1#column-15912776)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] ~[Aishwarya](https://github.com/hackforla/tables/issues/assigned/aishwaryaharikumar)~
       - [ ] [Bonnie](https://github.com/hackforla/tables/issues/assigned/ExperimentsInHonesty)
       - [ ] [Jessica C.](https://github.com/hackforla/tables/issues/assigned/jetchen08)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Bonnie to log in as host and make Jessica a host
- [ ] Walkthrough of end-to-end onboarding process so Jessica can make a process/systems diagram
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting
#### Recording
 - [ ] was there a recording made
 - [ ] did it get uploaded to the [folder](https://drive.google.com/drive/u/0/folders/1JkyEid3JMyXyXeQg7cn9m6nACv6CKP8F)

### Task Items

**Comment by jetchen08** [comment]
## 2024-02-15 Meeting Agenda

### Prework to prep for meeting
- [x] #30

### Recurring items:
 - [x] review any issues that are in the [new issue approval column](https://github.com/hackforla/tables/projects/1#column-15912776)
 - [x] Accountability and Support Check.
    - [x] Review assignments for each Team member
       - [x] [Lily Ng](https://github.com/hackforla/tables/issues/assigned/lilykat7)
       - [x] [Bonnie](https://github.com/hackforla/tables/issues/assigned/ExperimentsInHonesty)
       - [x] [Jessica C.](https://github.com/hackforla/tables/issues/assigned/jetchen08)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting
#### Recording
 - [ ] was there a recording made
 - [ ] did it get uploaded to the [folder](https://drive.google.com/drive/u/0/folders/1JkyEid3JMyXyXeQg7cn9m6nACv6CKP8F)

### Task Items

**Comment by lilykat7** [comment]
## 2024-02-22 Meeting Agenda

### Prework to prep for meeting
- [x] #30

### Recurring items:
 - [x] review any issues in [Q&A column](https://github.com/hackforla/tables/projects/1#column-15912779)
 - [x] review any issues that are in the [new issue approval column](https://github.com/hackforla/tables/projects/1#column-15912776)
 - [ ] Review issue for any new questions https://github.com/hackforla/tables/issues/54
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Lily Ng](https://github.com/hackforla/tables/issues/assigned/lilykat7)
       - [ ] [Bonnie](https://github.com/hackforla/tables/issues/assigned/ExperimentsInHonesty)
       - [ ] [Jessica C.](https://github.com/hackforla/tables/issues/assigned/jetchen08)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting
#### Recording
 - [ ] was there a recording made
 - [ ] did it get uploaded to the [folder](https://drive.google.com/drive/u/0/folders/1JkyEid3JMyXyXeQg7cn9m6nACv6CKP8F)

### Task Items

**Comment by ExperimentsInHonesty** [comment]
## 2024-02-29 Meeting Agenda

### Prework to prep for meeting
- [ ] #30

### Recurring items:
 - [ ] review any issues in [Q&A column](https://github.com/hackforla/tables/projects/1#column-15912779)
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/tables/projects/1#column-15912776)
 - [ ] Review issue for any new questions https://github.com/hackforla/tables/issues/54
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Lily Ng](https://github.com/hackforla/tables/issues/assigned/lilykat7)
       - [ ] [Bonnie](https://github.com/hackforla/tables/issues/assigned/ExperimentsInHonesty)
       - [ ] [Jessica C.](https://github.com/hackforla/tables/issues/assigned/jetchen08)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Review Lily's Notes about the Google Drive 600 people limitation issue
- [ ] Review overall slack bot
- [ ] Review if we should start knocking down the issues in the prioritized backlog for product or make new issues for developers
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting
#### Recording
 - [ ] was there a recording made
 - [ ] did it get uploaded to the [folder](https://drive.google.com/drive/u/0/folders/1JkyEid3JMyXyXeQg7cn9m6nACv6CKP8F)

### Task Items

**Comment by lilykat7** [comment]
## 2024-03-27 Meeting Agenda

### Prework to prep for meeting
- [ ] #30

### Recurring items:
 - [ ] review any issues in [Q&A column](https://github.com/hackforla/tables/projects/1#column-15912779)
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/tables/projects/1#column-15912776)
 - [ ] Review issue for any new questions https://github.com/hackforla/tables/issues/54
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Lily Ng](https://github.com/hackforla/tables/issues/assigned/lilykat7)
       - [ ] [Bonnie](https://github.com/hackforla/tables/issues/assigned/ExperimentsInHonesty)
       - [ ] [Jessica C.](https://github.com/hackforla/tables/issues/assigned/jetchen08)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
    - [ ] #56

### New Items
- [ ] Issue cleanup
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting
#### Recording
 - [ ] was there a recording made
 - [ ] did it get uploaded to the [folder](https://drive.google.com/drive/u/0/folders/1JkyEid3JMyXyXeQg7cn9m6nACv6CKP8F)

### Task Items

**Comment by lilykat7** [comment]
## 2024-04-11 Meeting Agenda

### Prework to prep for meeting
- [x] #30

### Recurring items:
 - [ ] review any issues in [Q&A column](https://github.com/hackforla/tables/projects/1#column-15912779)
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/tables/projects/1#column-15912776)
 - [ ] Review issue for any new questions https://github.com/hackforla/tables/issues/54
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Lily Ng](https://github.com/hackforla/tables/issues/assigned/lilykat7)
       - [ ] [Bonnie](https://github.com/hackforla/tables/issues/assigned/ExperimentsInHonesty)
       - [ ] [Jessica C.](https://github.com/hackforla/tables/issues/assigned/jetchen08)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting
#### Recording
 - [ ] was there a recording made
 - [ ] did it get uploaded to the [folder](https://drive.google.com/drive/u/0/folders/1JkyEid3JMyXyXeQg7cn9m6nACv6CKP8F)

### Task Items
